-- =============================================================================
-- Supabase Schema for Chicken Invaders Global Leaderboard
-- =============================================================================

-- 1. Create Leaderboard Table with validation constraints & country
CREATE TABLE IF NOT EXISTS leaderboard (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_name TEXT NOT NULL CHECK (char_length(player_name) BETWEEN 1 AND 25),
  score BIGINT NOT NULL CHECK (score >= 0),
  country TEXT DEFAULT '🌍',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE leaderboard ENABLE ROW LEVEL SECURITY;

-- 3. Policy: Anyone can read scores (public)
CREATE POLICY "Allow public read access"
  ON leaderboard FOR SELECT
  TO anon
  USING (true);

-- 4. Policy: Anyone can insert their score (public)
CREATE POLICY "Allow public insert access"
  ON leaderboard FOR INSERT
  TO anon
  WITH CHECK (
    char_length(player_name) BETWEEN 1 AND 25 AND
    score >= 0
  );

-- 5. Performance indices
CREATE INDEX IF NOT EXISTS idx_leaderboard_score_date ON leaderboard (score DESC, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_leaderboard_country_score ON leaderboard (country, score DESC, created_at ASC);

-- =============================================================================
-- MIGRATION: If your table already exists, run this in Supabase SQL Editor:
-- =============================================================================
-- ALTER TABLE leaderboard ADD COLUMN IF NOT EXISTS country TEXT DEFAULT '🌍';
